[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gts"
authors = [
    { name = "William Cleveland" },
    { name = "Adam Goldstein" },
    { name = "Daniel Kocevski" },
    { name = "Joshua Wood" },
    { email = "STI-Software@usra.edu" }
]
description = "Gamma-ray Targeted Search"
readme = "PYPI-README.rst"
license = "Apache-2.0"
license-files = ["license.txt"]
keywords = ['astronomy', 'gammaray', 'gamma-ray', 'usra']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Software Development :: Libraries",
]
requires-python = ">=3.11"
dependencies = [
    'astropy-healpix>=0.4',
    'astro-gdt-fermi',
    'numpy<2.4.0',
    'notebook',
    'ipywidgets'
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["Sphinx==5.0.2", "astropy-sphinx-theme", "nbsphinx", "sphinx-automodapi"]

[tool.setuptools]
include-package-data = true
script-files = ["scripts/gbm_targeted_search.py", "scripts/gts-download-responses"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"gts.data" = ['*.urls']

[tool.setuptools.dynamic]
version = { attr = "gts.core.__version__" }

[project.urls]
Documentation = 'https://astro-gdt.readthedocs.io/en/latest/'
Repository = 'https://github.com/USRA-STI/gdt-core'
Issues = 'https://github.com/USRA-STI/gdt-core/issues'

